version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml:ro
    networks:
      - trino-network

  hadoop-node:
    image: 'ghcr.io/trinodb/testing/hive3.1-hive:latest'
    hostname: hadoop-node
    ports:
      - '3306:3306' # Metastore MySQL Database
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '10000:10000' # HiveServer2
    volumes:
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
    networks:
      - trino-network

  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tiny
    ports:
      - '3307:3306'
    networks:
      - trino-network

  mongodb:
    image: 'mongo:latest'
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/database:/data/db
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - trino-network

volumes:
  minio-data:
    driver: local  

networks:
  trino-network:
    driver: bridge
